// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avucafcdirrtzhxcxqrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2dWNhZmNkaXJydHpoeGN4cXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzEyMzQsImV4cCI6MjA2MTkwNzIzNH0.dETnTmmzv61MFjuRCGLd8fdwZyEehoMXr8vjWHvG66I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);