
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Replace these with your self-hosted Supabase instance details
const SUPABASE_URL = "https://your-supabase-instance.com"; // Replace with your self-hosted URL
const SUPABASE_PUBLISHABLE_KEY = "your-anon-key-here"; // Replace with your anon/public key

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
